### ISSUE TITLE
ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by mg** [thlorenz/proxyquireify#21] opened 2014-11-30 21:29 UTC
Can't get rid of this error. Here's my package.json:
```
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "dependencies": {
  },
  "devDependencies": {
    "karma": "~0.12.25",
    "karma-jasmine": "~0.2.3",
    "karma-phantomjs-launcher": "~0.1.4",
    "karma-junit-reporter": "~0.2.2",
    "jshint-stylish": "~1.0.0",
    "browserify": "~6.3.3",
    "proxyquireify": "~1.1.0",
    "karma-browserify": "~1.0.0"
  }
}
```

karma.conf.js
```
module.exports = function(config) {
  config.set({
    basePath : '.',

    autoWatch : false,
    singleRun: true,

    frameworks: ['jasmine', 'browserify'],
    
    browsers : ['PhantomJS'],
    
    plugins : [
      'karma-browserify',
      'karma-jasmine',
      'karma-junit-reporter',
      'karma-phantomjs-launcher'
    ],

    preprocessors: {
      '*.spec.js': [ 'browserify' ]
    },

    browserify: {
      debug: true,
      plugin: ['proxyquireify/plugin']
    },

    junitReporter : {
      outputFile: 'test_out/unit.xml',
      suite: 'unit'
    },

    files: ['*.js']
  });
};
```

hello.js
```
exports= {
  hello: function() {
    return "hello";
  }
};
```

hello.spec.js
```
var proxyquire =  require('proxyquireify')(require);

describe('testing hello', function () {
	var Hello= proxyquire('./hello');

	it('should say hi', function() {
		expect(Hello.hell()).toBe('hello');
	});

});
```

Output from karma start karma.conf.js --log-level debug
```
DEBUG [config]: Loading config /Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/karma.conf.js
DEBUG [plugin]: Loading plugin karma-browserify.
DEBUG [plugin]: Loading plugin karma-jasmine.
DEBUG [plugin]: Loading plugin karma-junit-reporter.
DEBUG [plugin]: Loading plugin karma-phantomjs-launcher.
DEBUG [framework.browserify]: created browserify bundle: /var/folders/qg/r32h5c8s3sb5s4xy6lpthn680000gn/T/9409150f6698b81bf6aaf0b28d56eb7f01704769.browserify
DEBUG [framework.browserify]: no matching preprocessed file was found, defaulting to prepend
DEBUG [framework.browserify]: add bundle to config.files at position 0
INFO [karma]: Karma v0.12.28 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
DEBUG [temp-dir]: Creating temp dir at /var/folders/qg/r32h5c8s3sb5s4xy6lpthn680000gn/T/karma-5759403
DEBUG [launcher]: /Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs /var/folders/qg/r32h5c8s3sb5s4xy6lpthn680000gn/T/karma-5759403/capture.js
DEBUG [watcher]: Excluded file "/Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/karma.conf.js"
DEBUG [framework.browserify]: building bundle
DEBUG [framework.browserify]: adding hello.spec.js to bundle
DEBUG [framework.browserify]: bundling
INFO [framework.browserify]: 19474 bytes written (0.12 seconds)
INFO [framework.browserify]: bundle built
DEBUG [watcher]: Resolved files:
	/var/folders/qg/r32h5c8s3sb5s4xy6lpthn680000gn/T/9409150f6698b81bf6aaf0b28d56eb7f01704769.browserify
	/Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/node_modules/karma-jasmine/lib/jasmine.js
	/Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/node_modules/karma-jasmine/lib/boot.js
	/Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/node_modules/karma-jasmine/lib/adapter.js
	/Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/hello.js
	/Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/hello.spec.js
DEBUG [web-server]: serving: /Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/node_modules/karma/static/client.html
DEBUG [web-server]: serving: /Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/node_modules/karma/static/karma.js
DEBUG [web-server]: upgrade /socket.io/1/websocket/snH5FbsEJtcHVKNbf6AU
DEBUG [karma]: A browser has connected on socket snH5FbsEJtcHVKNbf6AU
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket snH5FbsEJtcHVKNbf6AU with id 5759403
DEBUG [launcher]: PhantomJS (id 5759403) captured in 2.082 secs
DEBUG [web-server]: serving: /Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/node_modules/karma/static/context.html
DEBUG [web-server]: serving (cached): /var/folders/qg/r32h5c8s3sb5s4xy6lpthn680000gn/T/9409150f6698b81bf6aaf0b28d56eb7f01704769.browserify
DEBUG [web-server]: serving (cached): /Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/node_modules/karma-jasmine/lib/jasmine.js
DEBUG [web-server]: serving (cached): /Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/hello.spec.js
DEBUG [web-server]: serving (cached): /Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/node_modules/karma-jasmine/lib/boot.js
DEBUG [web-server]: serving (cached): /Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/node_modules/karma-jasmine/lib/adapter.js
DEBUG [web-server]: serving (cached): /Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/hello.js
PhantomJS 1.9.8 (Mac OS X) ERROR
  ReferenceError: Can't find variable: require
  at /Users/magnusorngylfason/Google Drive/Business/Shopping Network/Code/browserifytest/hello.spec.js:1


DEBUG [karma]: Run complete, exiting.
DEBUG [launcher]: Disconnecting all browsers
DEBUG [framework.browserify]: cleaning up
DEBUG [launcher]: Process PhantomJS exited with code 0
DEBUG [temp-dir]: Cleaning temp dir /var/folders/qg/r32h5c8s3sb5s4xy6lpthn680000gn/T/karma-5759403
```

Any ideas? This has been driving my crazy all weekend.

**Comment by bendrucker** [comment] 2015-01-13 02:24
This should be a relatively easy fix on proxyquireify's end of things. Basically the prelude replacement code needs to check `b._expose`. If it's empty, `require` won't be global normally and the replacement doesn't need to be either. If it has any keys, then `newRequire` needs to be on the `window` with as `b._options.externalRequireName` (`'require'` by default). 

If you want details on why karma-browserify exposes your test files, read on:

<hr>

I'm a maintainer over at karma-browserify and just wanted to weigh in on exactly what's going on here and especially speak to the questions Thorsten raised in https://github.com/thlorenz/proxyquireify/issues/21#issuecomment-66531714. karma-browserify is essentially a collection of hacks that deals with shortcomings in the Karma API and quirks in the Browserify API. 

The core issue is that portion of Karma's API that allows for changing the files that it synchronizes with the browser is synchronous. The framework API was designed for things like `karma-mocha` which just needs to add two static scripts: mocha and some glue between the Mocha API and the Karma browser API. karma-browserify isn't that simple. Generating the bundle is async. The preprocessor API in Karma (e.g. compiling CoffeeScript to JS) is async.

karma-browserify is typically receiving a glob of files that matches multiple test files. Then this is what it does:

1. Generates a random filename and adds that to Karma's file list (framework)
2. Begins receiving calls to preprocess your test files (preprocessor)
3. Adds these files to the random, static bundle file, exposing them as their absolute paths
4. In place of the actual content, passes `'require(' + path ')'` back to Karma

On top of this, it hacks in a preprocessor for the randomized static bundle. This preprocessor is basically there to hold up Karma until the initial bundle has finished. This is why, when in doubt, you design your APIs to be async.

**Comment by thlorenz** [comment] 2015-01-13 03:20
Seems like a weird quirk with karma-browserify/karma then.
Possibly ask them to fix/remove some of their hacks?

If there is a straightforward solution we could apply to proxyquireify to fix this I'm open to it, but seems like we'd have to fix one hack with another ugly hack.

I'm leaning towards closing this, @bendrucker if you agree go ahead and do so.
Thanks.

**Comment by thlorenz** [comment] 2015-01-13 03:23
> This should be a relatively easy fix on proxyquireify's end of things

If anyone wants to stab at this however I'm open to merging this in (as long as its not too ugly and won't potentially cause problems in other cases).

**Comment by bendrucker** [comment] 2015-01-13 03:23
Yeah unfortunately it's a karma thing and karma-browserify is hacky because that's the only way to go.

I just dug in and this is a proxyquireify bug and a one line fix :)

Wait til you see

**Comment by bendrucker** [comment] 2015-01-13 03:42
So technically it was a 2 line fix :smile: 

My missive about the crazy hoops karma-browserify jumps through above was totally unnecessary. This was just an obscure proxyquireify bug. Commit message describes the issue if anyone cares to take a look for themselves.

**Closed** 2015-01-13 04:07 UTC

**Comment by Dakuan** [comment] 2015-01-13 14:01
bad news: Anyone using @git-jiby-me 's patch will find their lives ruined by the v1.2.0 
good news: You can just remove the patch entirely and everything will be fine!

**Comment by bendrucker** [comment] 2015-01-13 14:05
This is why the advice on the SO post is bad. If you catch a bug in a project and need to hotfix it you should always fork and use a git dep.

**Comment by thlorenz** [comment] 2015-01-13 14:05
@Dakuan so removing that patch and using the latest proxyquireify version makes it work with karma for you as well?

**Comment by Dakuan** [comment] 2015-01-13 14:33
@thlorenz correct!

**Comment by thlorenz** [comment] 2015-01-13 15:33
Ok, I left [a comment](http://stackoverflow.com/questions/27170117/require-not-defined-when-testing-with-proxyquireify-stubs/27410213#comment44248308_27410213) on the stackoverflow answer.
